### ISSUE TITLE
Create Installation and Deployment page on Wiki

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-legacy-solr#97]
### 💡 Description

We need detailed deployment and installation instructions

### ⚔️ Sub-tasks

- [x] Create wiki page and setup scripts
- [x] Procedure

### Deployment and Init Procedure
- [x] Cleanup legacy registry components
   - [x] harvest-pds3 (cli)
   - [x] harvest-pds4 (cli)
   - [x] registry-pds3 (tomcat)
   - [x] registry-pds4 (tomcat)
   - [x] registry-ads (tomcat)
   - [x] prod (tomcat)
   - [x] product (tomcat)
   - [x] registry-ui (tomcat)
   - [x] search-service (tomcat)
   - [x] transport-upload (tomcat)
   - [x] transport-registry (tomcat)
   - [x] search-ui (tomcat)
   - [x] storage-service (tomcat)
   - [x] search-core (cli)
   - [ ] all of the above from usr local
- [x] Follow Legacy Registry Installation and Deployment wiki - 4.0.4
   * To consider: DSIO-4952
- [x] Deploy latest ds-view - 2.18.0
- [x] Deploy latest search-ui-legacy - 2.2.1
   - [x] update Catalina/localhost/search-ui.xml -> Catalina/localhost/search-ui-legacy.xml
   - [x] update path in the file to point to new location
- [x] Update proxy
- [x] Run smoke test

**Comment by jordanpadams** [comment]
* Wiki page created titled: "https://github.com/NASA-PDS/search-ui-legacy"
* Init scripts created https://github.com/nasa-pds-engineering-node/registry-legacy-solr-config
